### ISSUE TITLE
Verify that the config file loaded up a curState for the ControllerStateMachine and check some other things to make sure the program is able to do things with that config file.

### ISSUE THREAD

**Issue by jawaff** [WaffleTime/KinectController#11]
Basically we need to verify that the config file is valid and meets the requirements of the program so that the program can make basic assumptions and not worry about exceptions later on.

**Comment by rsspiekerman** [comment]
Holy crap, you've been busy! I finally managed to get the time to get back
to my e-mails and was blown away. Thank you for the updates; I've been
thinking about this project too and working on my understanding of Java in
the meantime, but it sounds like you have more than enough understanding
for the both of us.

**Comment by jawaff** [comment]
Hi Ryan!

I'm closing this issue because issue #32 seems to have taken over the issue of working out how to validate the config files.
